apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd-system # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
type: Opaque
