# The service account, cluster roles, and cluster role binding are
# only needed for Kubernetes with role-based access control (RBAC).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: flux-system
  labels:
    name: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flux
  labels:
    name: flux
rules:
- resources: ['*']
  apiGroups: ['*']
  verbs: ['*']
- nonResourceURLs: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    name: flux
roleRef:
  name: flux
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: flux
  namespace: flux-system
  kind: ServiceAccount
